<section class="login animated fadeIn">
    <img class="svg" src="/img/l_mark-votr.svg" />
    <h1>Forgot Your Password??</h1>
    <p>Enter your email address below, and we'll email you instructions on how to change your password.</p>
    <div class="field">
        <label for="login-email" class="visuallyhidden">Email Address</label>
        <input id="login-email" type="email" placeholder="Email Address" />
    </div>
    <input type="submit" value="Request Password" />
    <!-- if there's an error, use the following
    <input class="animated shake" type="submit" value="Request Password" />
    -->
</section>