<section class="login animated fadeIn">
    <img class="svg" src="/img/l_mark-fzyskeleton.svg" />
    <h1>Please Log In</h1>
    <div class="field">
        <label for="login-email" class="visuallyhidden">Email Address</label>
        <input id="login-email" type="email" placeholder="Email Address" />
    </div>
    <div class="field">
        <label for="login-password" class="visuallyhidden">Password</label>
        <input id="login-password" type="password" placeholder="Password" />
        <a href="#">Forgot password?</a>
    </div>
    <input type="submit" value="Log In" />
    <!-- if there's an error, use the following
    <input class="animated shake" type="submit" value="Log In" />
    -->
</section>