<?php if ( $this->zfcUserIdentity() != null): ?>
    <div class="user">
        <strong><?php echo $this->translate('User'); ?>:</strong>
        <a class="button primary" href="<?php echo $this->url('settings/user_profile'); ?>">
            <?php echo $this->zfcUserIdentity()->getFirstName(); ?>
            <?php echo $this->zfcUserIdentity()->getLastName(); ?>
        </a>
    </div>
<?php endif; ?>