<?php $this->inlineScript()->prependFile('/dist/js/app/controllers/OfficesListCtrl.js'); ?>

<?php if ($this->isAllowed('officeSelector','view')): ?>
    <div data-ng-cloak class="office" data-ng-controller="OfficesListCtrl" <?php echo $this->ngInit()->addItems($this->session()->getOffice()); ?>>

        <strong><?php echo $this->translate('Office'); ?>:</strong>

        {{office.officeNumber}}: {{office.name}}

        <?php if ($this->isAllowed('officeSelector','change')): ?>
            <button class="office-toggle" data-ng-click="display_office_list = !display_office_list"><img class="svg" src="/img/icons/i_down-arrow.svg" /></button>

            <ol class="office-list" data-ng-init="display_office_list = false" data-ng-show="display_office_list" data-ng-animate="animate">

                <li data-ng-repeat="o in offices" data-ng-class="{'selected' : o.id == office.id}">
                    <a data-ng-click="setOffice(o.id)">{{o.officeNumber}}: {{o.name}}</a>
                </li>

            </ol>
        <?php endif; ?>
    </div>
<?php endif; ?>
