<?php
$this->inlineScript()
    ->appendFile('/dist/js/app/controllers/ChangePasswordCtrl.js');
?>



<?php if ($this->success): ?>
    <div ng-controller="ChangePasswordController" ng-init=""></div>
<?php else: ?>
    <div ng-controller="ChangePasswordController" ng-init="init({'error':'Unable to change your password.'})"></div>
<?php endif; ?>

<?php if ($this->changePasswordForm !== null): ?>

    <?php
        $form = $this->changePasswordForm;

        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/changepassword'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('id', 'changepassword');
        $emailElement = $form->get('identity');
        $emailElement->setValue($this->zfcUserIdentity()->getEmail());
    ?>

    <section class="login animated fadeIn">
        <img class="svg" src="/img/l_mark-votr.svg" />
        <?php echo $this->form()->openTag($form) ?>
        <?php echo $this->formInput($form->get('identity')); ?>

        <h1><?php echo $this->translate('Change Password'); ?></h1>

        <div class="field">
            <label for="credential" class="visuallyhidden"><?php echo $this->translate('Current Password'); ?>:<em class="req">*</em></label>
            <?php echo $this->formInput($form->get('credential')); ?><small><strong>Required</strong></small>
            <div>
                <?php echo $this->formElementErrors()
                    ->setMessageOpenFormat('<strong class="error-message">')
                    ->setMessageSeparatorString('</strong><strong class="help-inline">')
                    ->setMessageCloseString('</strong>')
                    ->render($form->get('credential'));
                ?>
            </div>

        </div>

        <div class="field">
            <label for="newCredential" class="visuallyhidden"><?php echo $this->translate('New Password'); ?>:<em class="req">*</em></label>
            <?php echo $this->formInput($form->get('newCredential')); ?><small><strong>Required</strong></small>
            <div>
                <?php echo $this->formElementErrors()
                    ->setMessageOpenFormat('<strong class="error-message">')
                    ->setMessageSeparatorString('</strong><strong class="help-inline">')
                    ->setMessageCloseString('</strong>')
                    ->render($form->get('newCredential'));
                ?>
            </div>
        </div>

        <div class="field">
        <label for="firstNamenewCredentialVerify" class="visuallyhidden"><?php echo $this->translate('Verify New Password'); ?>:<em class="req">*</em></label>
            <?php echo $this->formInput($form->get('newCredentialVerify')); ?><small><strong>Required</strong></small>
            <div>
                <?php echo $this->formElementErrors()
                    ->setMessageOpenFormat('<strong class="error-message">')
                    ->setMessageSeparatorString('</strong><strong class="help-inline">')
                    ->setMessageCloseString('</strong>')
                    ->render($form->get('newCredentialVerify'));
                ?>
            </div>

        </div>

        <?php echo $this->formInput($form->get('submit')); ?>

        <?php echo $this->form()->closeTag() ?>

    </section>

<?php endif; ?>