<?php
    $form = $this->loginForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/login'));
    $form->setAttribute('method', 'post');
?>
<section class="login animated fadeIn">
    <img class="svg" src="/img/l_mark-votr.svg" />
    <?php echo $this->form()->openTag($form) ?>

    <h1><?php echo $this->translate('Please Login'); ?></h1>
    <div class="field">
        <label for="login-email" class="visuallyhidden"><?php echo $this->translate('Email Address'); ?></label>
        <?php echo $this->formInput($form->get('identity')) ?>
        <div>
        <?php echo $this->formElementErrors()
            ->setMessageOpenFormat('<strong class="error-message">')
            ->setMessageSeparatorString('</strong><strong class="help-inline">')
            ->setMessageCloseString('</strong>')
            ->render($form->get('identity'));
        ?>
        </div>
    </div>
    <div class="field">
        <label for="login-password" class="visuallyhidden"><?php echo $this->translate('Password'); ?></label>
        <?php echo $this->formInput($form->get('credential')) ?>
        <div>
        <?php echo $this->formElementErrors()
            ->setMessageOpenFormat('<strong class="error-message">')
            ->setMessageSeparatorString('</strong><strong class="help-inline">')
            ->setMessageCloseString('</strong>')
            ->render($form->get('credential'));
        ?>
        </div>
        <a href="<?php echo $this->url('password/forgot') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"> <?php echo $this->translate('Forgot password?'); ?> </a>
    </div>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>

    <?php echo $this->formInput($form->get('submit')) ?>
    <!-- if there's an error, use the following
    <input class="animated shake" type="submit" value="Log In" />
    -->
    <?php echo $this->form()->closeTag() ?>
</section>


