<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity\Base;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Claim extends \Application\Entity\Base\Claim implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'laFileNumber', 'office', 'dateAssigned', 'isClosed', 'dateClosed', 'settlementStatus', 'grossAmount', 'insuredFirstName', 'insuredLastName', 'insuredAddress', 'insuredContact', 'insuredNotes', 'copyInsuredAddress', 'lossAddress', 'claimantFirstName', 'claimantLastName', 'policyNumber', 'policyDateStart', 'policyDateEnd', 'lossDate', 'lossType', 'catastropheNumber', 'claimantFullName', 'claimantContact', 'lossLocationNotes', 'company', 'claimNumber', 'attention', 'reserve', 'claimSource', 'companyContact', 'insuranceNotes', 'agent', 'agentAssignedBy', 'agentContact', 'agentNotes', 'adjuster', 'activityLocation', 'adjusterDiaryDate', 'supervisorDiaryDate', 'photos', 'attachments', 'createdBy', 'createdTs', 'updatedBy', 'updatedTs', 'invoices', 'userCanEdit', 'deleted', 'id', 'dateFormatFlat');
        }

        return array('__isInitialized__', 'laFileNumber', 'office', 'dateAssigned', 'isClosed', 'dateClosed', 'settlementStatus', 'grossAmount', 'insuredFirstName', 'insuredLastName', 'insuredAddress', 'insuredContact', 'insuredNotes', 'copyInsuredAddress', 'lossAddress', 'claimantFirstName', 'claimantLastName', 'policyNumber', 'policyDateStart', 'policyDateEnd', 'lossDate', 'lossType', 'catastropheNumber', 'claimantFullName', 'claimantContact', 'lossLocationNotes', 'company', 'claimNumber', 'attention', 'reserve', 'claimSource', 'companyContact', 'insuranceNotes', 'agent', 'agentAssignedBy', 'agentContact', 'agentNotes', 'adjuster', 'activityLocation', 'adjusterDiaryDate', 'supervisorDiaryDate', 'photos', 'attachments', 'createdBy', 'createdTs', 'updatedBy', 'updatedTs', 'invoices', 'userCanEdit', 'deleted', 'id', 'dateFormatFlat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Claim $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function flatten()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'flatten', array());

        return parent::flatten();
    }

    /**
     * {@inheritDoc}
     */
    public function getLaFileNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaFileNumber', array());

        return parent::getLaFileNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaFileNumber($laFileNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaFileNumber', array($laFileNumber));

        return parent::setLaFileNumber($laFileNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function setOffice(\Application\Entity\Base\OfficeInterface $office)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffice', array($office));

        return parent::setOffice($office);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffice', array());

        return parent::getOffice();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsuredAddress(\Application\Entity\Base\AddressInterface $insuredAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsuredAddress', array($insuredAddress));

        return parent::setInsuredAddress($insuredAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsuredAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsuredAddress', array());

        return parent::getInsuredAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivityLocation($activityLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivityLocation', array($activityLocation));

        return parent::setActivityLocation($activityLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityLocation', array());

        return parent::getActivityLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdjuster(\Application\Entity\Base\AdjusterInterface $adjuster)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdjuster', array($adjuster));

        return parent::setAdjuster($adjuster);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjuster()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjuster', array());

        return parent::getAdjuster();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdjusterDiaryDate($adjusterDiaryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdjusterDiaryDate', array($adjusterDiaryDate));

        return parent::setAdjusterDiaryDate($adjusterDiaryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjusterDiaryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjusterDiaryDate', array());

        return parent::getAdjusterDiaryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgent(\Application\Entity\Base\AgentInterface $agent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgent', array($agent));

        return parent::setAgent($agent);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgent', array());

        return parent::getAgent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgentAssignedBy($agentAssignedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgentAssignedBy', array($agentAssignedBy));

        return parent::setAgentAssignedBy($agentAssignedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgentAssignedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgentAssignedBy', array());

        return parent::getAgentAssignedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgentContact(\Application\Entity\Base\ContactInterface $agentContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgentContact', array($agentContact));

        return parent::setAgentContact($agentContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgentContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgentContact', array());

        return parent::getAgentContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgentNotes($agentNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgentNotes', array($agentNotes));

        return parent::setAgentNotes($agentNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgentNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgentNotes', array());

        return parent::getAgentNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttention($attention)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttention', array($attention));

        return parent::setAttention($attention);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttention', array());

        return parent::getAttention();
    }

    /**
     * {@inheritDoc}
     */
    public function setCatastropheNumber($catastropheNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCatastropheNumber', array($catastropheNumber));

        return parent::setCatastropheNumber($catastropheNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCatastropheNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatastropheNumber', array());

        return parent::getCatastropheNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaimNumber($claimNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaimNumber', array($claimNumber));

        return parent::setClaimNumber($claimNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaimNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaimNumber', array());

        return parent::getClaimNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaimSource($claimSource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaimSource', array($claimSource));

        return parent::setClaimSource($claimSource);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaimSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaimSource', array());

        return parent::getClaimSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaimantContact(\Application\Entity\Base\ContactInterface $claimantContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaimantContact', array($claimantContact));

        return parent::setClaimantContact($claimantContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaimantContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaimantContact', array());

        return parent::getClaimantContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaimantFirstName($claimantFirstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaimantFirstName', array($claimantFirstName));

        return parent::setClaimantFirstName($claimantFirstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaimantFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaimantFirstName', array());

        return parent::getClaimantFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaimantFullName($claimantFullName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaimantFullName', array($claimantFullName));

        return parent::setClaimantFullName($claimantFullName);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaimantFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaimantFullName', array());

        return parent::getClaimantFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaimantLastName($claimantLastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaimantLastName', array($claimantLastName));

        return parent::setClaimantLastName($claimantLastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaimantLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaimantLastName', array());

        return parent::getClaimantLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany(\Application\Entity\Base\CompanyInterface $company)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', array($company));

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', array());

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyContact(\Application\Entity\Base\ContactInterface $companyContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyContact', array($companyContact));

        return parent::setCompanyContact($companyContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyContact', array());

        return parent::getCompanyContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAssigned($dateAssigned)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAssigned', array($dateAssigned));

        return parent::setDateAssigned($dateAssigned);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAssigned()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAssigned', array());

        return parent::getDateAssigned();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateClosed($dateClosed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateClosed', array($dateClosed));

        return parent::setDateClosed($dateClosed);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateClosed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateClosed', array());

        return parent::getDateClosed();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrossAmount($grossAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrossAmount', array($grossAmount));

        return parent::setGrossAmount($grossAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrossAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrossAmount', array());

        return parent::getGrossAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsuranceNotes($insuranceNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsuranceNotes', array($insuranceNotes));

        return parent::setInsuranceNotes($insuranceNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsuranceNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsuranceNotes', array());

        return parent::getInsuranceNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsuredContact(\Application\Entity\Base\ContactInterface $insuredContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsuredContact', array($insuredContact));

        return parent::setInsuredContact($insuredContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsuredContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsuredContact', array());

        return parent::getInsuredContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsuredFirstName($insuredFirstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsuredFirstName', array($insuredFirstName));

        return parent::setInsuredFirstName($insuredFirstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsuredFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsuredFirstName', array());

        return parent::getInsuredFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsuredLastName($insuredLastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsuredLastName', array($insuredLastName));

        return parent::setInsuredLastName($insuredLastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsuredLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsuredLastName', array());

        return parent::getInsuredLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsuredNotes($insuredNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsuredNotes', array($insuredNotes));

        return parent::setInsuredNotes($insuredNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsuredNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsuredNotes', array());

        return parent::getInsuredNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsClosed($isClosed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsClosed', array($isClosed));

        return parent::setIsClosed($isClosed);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsClosed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsClosed', array());

        return parent::getIsClosed();
    }

    /**
     * {@inheritDoc}
     */
    public function setLossAddress(\Application\Entity\Base\AddressInterface $lossAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLossAddress', array($lossAddress));

        return parent::setLossAddress($lossAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getLossAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLossAddress', array());

        return parent::getLossAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setLossDate($lossDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLossDate', array($lossDate));

        return parent::setLossDate($lossDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLossDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLossDate', array());

        return parent::getLossDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLossLocationNotes($lossLocationNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLossLocationNotes', array($lossLocationNotes));

        return parent::setLossLocationNotes($lossLocationNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getLossLocationNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLossLocationNotes', array());

        return parent::getLossLocationNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setLossType(\Application\Entity\Base\LossInterface $lossType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLossType', array($lossType));

        return parent::setLossType($lossType);
    }

    /**
     * {@inheritDoc}
     */
    public function getLossType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLossType', array());

        return parent::getLossType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolicyDateEnd($policyDateEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolicyDateEnd', array($policyDateEnd));

        return parent::setPolicyDateEnd($policyDateEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPolicyDateEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolicyDateEnd', array());

        return parent::getPolicyDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolicyDateStart($policyDateStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolicyDateStart', array($policyDateStart));

        return parent::setPolicyDateStart($policyDateStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getPolicyDateStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolicyDateStart', array());

        return parent::getPolicyDateStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolicyNumber($policyNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolicyNumber', array($policyNumber));

        return parent::setPolicyNumber($policyNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPolicyNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolicyNumber', array());

        return parent::getPolicyNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve($reserve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve', array($reserve));

        return parent::setReserve($reserve);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve', array());

        return parent::getReserve();
    }

    /**
     * {@inheritDoc}
     */
    public function setSettlementStatus(\Application\Entity\Base\StatusInterface $settlementStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSettlementStatus', array($settlementStatus));

        return parent::setSettlementStatus($settlementStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getSettlementStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettlementStatus', array());

        return parent::getSettlementStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupervisorDiaryDate($supervisorDiaryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupervisorDiaryDate', array($supervisorDiaryDate));

        return parent::setSupervisorDiaryDate($supervisorDiaryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupervisorDiaryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupervisorDiaryDate', array());

        return parent::getSupervisorDiaryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoCount', array());

        return parent::getPhotoCount();
    }

    /**
     * {@inheritDoc}
     */
    public function hasPhoto(\Application\Entity\Base\Claim\PhotoInterface $photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPhoto', array($photo));

        return parent::hasPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotos', array());

        return parent::getPhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhoto(\Application\Entity\Base\Claim\PhotoInterface $photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhoto', array($photo));

        return parent::addPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhoto(\Application\Entity\Base\Claim\PhotoInterface $photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhoto', array($photo));

        return parent::removePhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function addPhotos(\Doctrine\Common\Collections\Collection $photos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhotos', array($photos));

        return parent::addPhotos($photos);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhotos(\Doctrine\Common\Collections\Collection $photos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhotos', array($photos));

        return parent::removePhotos($photos);
    }

    /**
     * {@inheritDoc}
     */
    public function clearPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearPhotos', array());

        return parent::clearPhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachmentCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachmentCount', array());

        return parent::getAttachmentCount();
    }

    /**
     * {@inheritDoc}
     */
    public function hasAttachment(\Application\Entity\Base\Claim\AttachmentInterface $attachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAttachment', array($attachment));

        return parent::hasAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', array());

        return parent::getAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttachment(\Application\Entity\Base\Claim\AttachmentInterface $attachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttachment', array($attachment));

        return parent::addAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function addAttachments(\Doctrine\Common\Collections\Collection $attachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttachments', array($attachments));

        return parent::addAttachments($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttachment(\Application\Entity\Base\Claim\AttachmentInterface $attachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttachment', array($attachment));

        return parent::removeAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttachments(\Doctrine\Common\Collections\Collection $attachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttachments', array($attachments));

        return parent::removeAttachments($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function clearAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearAttachments', array());

        return parent::clearAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\Application\Entity\Base\UserInterface $createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedTs($createdTs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedTs', array($createdTs));

        return parent::setCreatedTs($createdTs);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedTs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedTs', array());

        return parent::getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(\Application\Entity\Base\UserInterface $updatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', array($updatedBy));

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', array());

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedTs($updatedTs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedTs', array($updatedTs));

        return parent::setUpdatedTs($updatedTs);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedTs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedTs', array());

        return parent::getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoices', array());

        return parent::getInvoices();
    }

    /**
     * {@inheritDoc}
     */
    public function hasInvoice(\Application\Entity\Base\Claim\InvoiceInterface $invoice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasInvoice', array($invoice));

        return parent::hasInvoice($invoice);
    }

    /**
     * {@inheritDoc}
     */
    public function addInvoice(\Application\Entity\Base\Claim\InvoiceInterface $invoice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInvoice', array($invoice));

        return parent::addInvoice($invoice);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInvoice(\Application\Entity\Base\Claim\InvoiceInterface $invoice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInvoice', array($invoice));

        return parent::removeInvoice($invoice);
    }

    /**
     * {@inheritDoc}
     */
    public function countInvoices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'countInvoices', array());

        return parent::countInvoices();
    }

    /**
     * {@inheritDoc}
     */
    public function clearInvoices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearInvoices', array());

        return parent::clearInvoices();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCanEdit($userCanEdit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCanEdit', array($userCanEdit));

        return parent::setUserCanEdit($userCanEdit);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCanEdit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCanEdit', array());

        return parent::getUserCanEdit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'id', array());

        return parent::id();
    }

    /**
     * {@inheritDoc}
     */
    public function isNull()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNull', array());

        return parent::isNull();
    }

    /**
     * {@inheritDoc}
     */
    public function flatCollection($collection, $extended = false, $indexById = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'flatCollection', array($collection, $extended, $indexById));

        return parent::flatCollection($collection, $extended, $indexById);
    }

    /**
     * {@inheritDoc}
     */
    public function asDoctrineProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'asDoctrineProperty', array());

        return parent::asDoctrineProperty();
    }

    /**
     * {@inheritDoc}
     */
    public function addSelfTo(\Doctrine\Common\Collections\Collection $collection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSelfTo', array($collection));

        return parent::addSelfTo($collection);
    }

    /**
     * {@inheritDoc}
     */
    public function nullGet($className, \Application\Entity\BaseInterface $entity = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nullGet', array($className, $entity));

        return parent::nullGet($className, $entity);
    }

    /**
     * {@inheritDoc}
     */
    public function tsSet($ts, $createIfEmpty = true, $timezone = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tsSet', array($ts, $createIfEmpty, $timezone));

        return parent::tsSet($ts, $createIfEmpty, $timezone);
    }

    /**
     * {@inheritDoc}
     */
    public function tsGet(\DateTime $tsProperty = NULL, $createIfEmpty = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tsGet', array($tsProperty, $createIfEmpty));

        return parent::tsGet($tsProperty, $createIfEmpty);
    }

    /**
     * {@inheritDoc}
     */
    public function tsGetFormatted(\DateTime $tsProperty = NULL, $format, $timezone = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tsGetFormatted', array($tsProperty, $format, $timezone));

        return parent::tsGetFormatted($tsProperty, $format, $timezone);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormTag', array());

        return parent::getFormTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormTag($tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormTag', array($tag));

        return parent::setFormTag($tag);
    }

}
